version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    target-branch: "dev"
    reviewers:
     - "shchen-idmod"
     - "ZDu-idm"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    ignore:
      # Optional: example of skipping major version bumps
      - dependency-name: "numpy"
        update-types: [ "version-update:semver-major" ]
