name: Deploy Packages
on:
  push:
    branches: [main]
    tags: ['v*']
  workflow_dispatch:
    inputs:
      target:
        description: 'Where to upload'
        required: false
        default: 'test'
        type: choice
        options: [test, prod]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [core, cli, models, platform_comps, platform_general, platform_slurm, platform_container, test]
    if: |
      github.event_name == 'workflow_dispatch' ||
      startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools-scm twine
      - name: Lint & test
        working-directory:  idmtools_${{ matrix.package }}
        run: |
          pip install black flake8 pytest
#          black --check .
#          flake8 .
#          run:
#          pytest tests || true
      - name: Build
        working-directory: idmtools_${{ matrix.package }}
        env:
          SETUPTOOLS_SCM_LOCAL_SCHEME_OVERRIDE: no-local-version
        run: python -m build

      # Upload artifacts for the publish job
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-idmtools_${{ matrix.package }}
          path: idmtools_${{ matrix.package }}/dist/
          retention-days: 1

      - name: Upload to TestPyPI
        if: github.event_name == 'workflow_dispatch' && inputs.target == 'test'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          packages-dir: idmtools_${{ matrix.package }}/dist/
          skip-existing: true
          verbose: true

  publish-to-pypi:
    needs: build
    runs-on: ubuntu-latest
    environment: deploy_pypi  # Manual approval required here
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        package: [core, cli, models, platform_comps, platform_general, platform_slurm, platform_container, test]
    steps:
      # Download the pre-built artifacts
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-idmtools_${{ matrix.package }}
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          user: __token__
#          password: ${{ secrets.PYPI_API_TOKEN }}
#          packages-dir: dist/
#          verbose: true