# This workflows will download idmtools nightly packages from artifactory then run smoke tests

name: "run-nightly-build-smoke-test-cron"

on:
  schedule:
    # Run at 6AM PST (13 UTC time) on Monday, Wednesday, and Friday
    - cron: '0 13 * * 1,3,5'

jobs:
  run-nightly-build-smoke-test-cron:
    if: github.repository == 'InstituteforDiseaseModeling/idmtools'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]
    env:
      bamboo_user: ${{ secrets.PYPI_STAGING_USERNAME }}
      bamboo_password: ${{ secrets.PYPI_STAGING_PASSWORD }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: ${{ matrix.os }} Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install idm-buildtools flake8 --index-url=https://packages.idmod.org/api/pypi/pypi-production/simple
      - name: Install dataclass
        if: ${{ matrix.python-version }} == 3.6
        run: |
          pip install dataclasses
      - name: download idmtools packages from staging jfrog
        run: |
          pip install idmtools[full] --index-url=https://${{ env.bamboo_user }}:${{ env.bamboo_password }}@packages.idmod.org/api/pypi/pypi-staging/simple
          pip install idmtools-test --index-url=https://${{ env.bamboo_user }}:${{ env.bamboo_password }}@packages.idmod.org/api/pypi/pypi-staging/simple
          pip install idmtools[test] --index-url=https://${{ env.bamboo_user }}:${{ env.bamboo_password }}@packages.idmod.org/api/pypi/pypi-staging/simple
      - name: login to comps2
        run: |
          python dev_scripts/create_auth_token_args.py --username $COMPS_USER --password $COMPS_PASSWORD
        env:
          COMPS_USER: ${{ secrets.COMPS_USER }}
          COMPS_PASSWORD: ${{ secrets.COMPS_PASSWORD }}
      - name: login to docker staging
        run: |
          echo '${{ env.bamboo_password }}' | docker login idm-docker-staging.packages.idmod.org --username ${{ env.bamboo_user }} --password-stdin
      - name: run idmtools_cli smoke tests
        run: |
          cd idmtools_cli
          make test-smoke
      - name: Upload idmtools_cli all smoke test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: idmtools_cli_test_results
          path: idmtools_cli/tests/reports/
      - name: run idmtools_core smoke tests
        run: |
          cd idmtools_core
          make test-smoke
      - name: Upload idmtools_core all smoke test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: idmtools_core_test_results
          path: idmtools_core/tests/reports/
      - name: run idmtools_models smoke tests
        run: |
          cd idmtools_models
          make test-smoke
      - name: Upload idmtools_models all smoke test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: idmtools_models_test_results
          path: idmtools_models/tests/results/
      - name: run idmtools_platform_comps smoke tests
        run: |
          cd idmtools_platform_comps
          make test-smoke
      - name: Upload idmtools_platform_comps smoke test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: idmtools_platform_comps_test_results
          path: idmtools_platform_comps/tests/results/
      - name: run idmtools_platform_local smoke tests
        run: |
          cd idmtools_platform_local
          make test-smoke
      - name: Upload idmtools_platform_local all smoke test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: idmtools_platform_local_test_results
          path: idmtools_platform_local/tests/results/